<form id="form1" name="form1" action='<?php echo $this->element->getAction(); ?>' method= '<?php echo $this->element->getMethod(); ?>'>
  <table width="393" border="0" align="center" cellpadding="0" cellspacing="0" class="tb_login">
    <tr>
      <td width="153" height="98">&nbsp;</td>
      <td width="181">&nbsp;</td>
      <td width="59">&nbsp;</td>
    </tr>
    <tr>
      <td height="29">&nbsp;</td>
      <td><?php echo $this->element->email;?></td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td height="27">&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td height="30">&nbsp;</td>
      <td><?php echo $this->element->password;?></td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td height="21">&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td height="41"></td>
      <td><?php echo $this->element->signin;?></td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
  </table>
</form>