<?php echo $this->doctype() ?>
<html>
    <meta charset="utf-8"/>
    <head>   
        <?php echo $this->headTitle() ?>   
        <?php echo $this->headMeta() ?>        
        <?php echo $this->headLink() ?>   
        <?php echo $this->headScript() ?>
        <style>
            #container{
                position:fixed;top:30%;left:50%;margin:-50px 0 0 -150px;
            }    
        </style>      
    </head>
    <body>
        <div id="container" align="center">
            <div id="loading_" ><?php
                $errorsMessages = $this->form->getMessages();
                if (isset($errorsMessages['email']['isEmpty'])||isset($errorsMessages['password']['isEmpty'])) {
                    echo '<div class="alert alert-error">
                        <a class="close" data-dismiss="alert" onclick="$(this).parent().slideUp();return false;">×</a>
                        <strong>Vui lòng nhập thông tin đăng nhập.</strong>
                      </div>';
                }
                else {
                    if (isset($this->errorMessage)) {
                        echo $this->errorMessage;
                    }
                }
                ?></div>
            <?php echo $this->form; ?>
        </div>
    </body>
</html>
