<?php echo $this->doctype() ?>
<html>
    <head> 
        <meta http-equiv="Content-Language" content="VN" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <?php echo $this->headTitle() ?>   
        <?php echo $this->headMeta() ?>        
        <?php echo $this->headLink() ?>   
        <?php echo $this->headScript() ?>
        <style>
            #container {
                width: 100%;
            }
            #sidebar {
                position: fixed;
                left: 0;
                top: 44px;
                bottom: 0;
                z-index: 1;
                border:1px solid #ededed;
                width: 160px;
                padding: 40px; 
            }
            #content {
                margin: 50px 0px 0px 245px;
                position: relative;
            }
            #data{
                position: relative;
                overflow: hidden;
                height: auto;
            }
            #top{
                height: 44px;
                position: fixed;
                width: 100%;
                min-width: 320px;
                top: 0;
                background-color: #fff;
                left: 0;
                z-index: 2;
                background-color: #F5F5F5;
                border-bottom: 3px solid #1D98BC;
            }
            #footer{
                padding: 10px 0;
                height: 25px;
                border-top: solid 1px #c9c9c9;
                font-size: 11px;
                color: #000000;
                position: fixed;
                bottom: 0px;
                width: 100%;
                margin-left: 242px;
                background-color:white;
                z-index: 3;
                -webkit-box-shadow: 0 5px 5px -5px #777;
                -moz-box-shadow: 0 5px 5px -5px #777;
                box-shadow: 0 5px 5px -5px #777;
            }

            /* common and top level styles */
            #nav span {
                display: none;
            }
            #nav, #nav ul {
                list-style: none outside none;
                margin: 0;
                padding: 0;
            }
            #nav {
                background-color:#F5F5F5;
                border-bottom: 2px solid #1D98BC;
                float: left;
                margin-left: 5px;
                margin-right: 1%;
                position: relative;
                width: auto;
            }
            #nav ul.subs {
                background-color: #FFFFFF;
                box-shadow: 1px 1px 5px rgba(0, 0, 0, 0.2);
                color: #333333;
                display: none;
                left: 0;
                padding: 2%;
                position: absolute;
                top: 54px;
                width: 96%;
            }
            #nav > li {
                border-bottom: 5px solid transparent;
                float: left;
                margin-bottom: -5px;
                text-align: left;
                -moz-transition: all 300ms ease-in-out 0s;
                -ms-transition: all 300ms ease-in-out 0s;
                -o-transition: all 300ms ease-in-out 0s;
                -webkit-transition: all 300ms ease-in-out 0s;
                transition: all 300ms ease-in-out 0s;
            }
            #nav li a {
                display: block;
                text-decoration: none;
                -moz-transition: color 450ms ease-in-out 0s, background-color 450ms ease-in-out 0s;
                -ms-transition: color 450ms ease-in-out 0s, background-color 450ms ease-in-out 0s;
                -o-transition: color 450ms ease-in-out 0s, background-color 450ms ease-in-out 0s;
                -webkit-transition: color 450ms ease-in-out 0s, background-color 450ms ease-in-out 0s;
                transition: color 450ms ease-in-out 0s, background-color 450ms ease-in-out 0s;
                white-space: normal;
            }
            #nav > li > a {
                font-family:Georgia,Arial,serif;
                color: #333333;
                display: block;
                font-size: 20px;
                line-height: 44px;
                padding: 0 15px;
                outline: 0 none;
                text-transform: uppercase;
            }
            #nav > li:hover > a, #nav > a:hover {
                font-family:Georgia,Arial,serif;
                background-color: #22AED7;
                color: #FFFFFF;
            }
            #nav li.active > a {
                background-color:  #1F9FC5;
                color: #FFFFFF;
            }

            /* submenu */
            #nav li:hover ul.subs {
                display: block;
            }
            #nav ul.subs > li {
                display: inline-block;
                float: none;
                padding: 10px 1%;
                vertical-align: top;
                width: 33%;
            }
            #nav ul.subs > li a {
                color: #777777;
                line-height: 20px;
            }
            #nav ul li a:hover {
                color: #F55856;
            }
            #nav ul.subs > li > a {
                font-size: 20px;
                margin-bottom: 10px;
                text-transform: uppercase;
            }
            #nav ul.subs > li li {
                float: none;
                padding-left: 8px;
                -moz-transition: padding 150ms ease-out 0s;
                -ms-transition: padding 150ms ease-out 0s;
                -o-transition: padding 150ms ease-out 0s;
                -webkit-transition: padding 150ms ease-out 0s;
                transition: padding 150ms ease-out 0s;
            }
            #nav ul.subs > li li:hover {
                padding-left: 15px;
            }

            /* responsive rules */
            @media all and (max-width : 980px) {
                #nav > li {
                    float: none;
                    border-bottom: 0;
                    margin-bottom: 0;
                }
                #nav ul.subs {
                    position: relative;
                    top: 0;
                }
                #nav li:hover ul.subs {
                    display: none;
                }
                #nav li #s1:target + ul.subs,
                #nav li #s2:target + ul.subs {
                    display: block;
                }

                #nav ul.subs > li {
                    display: block;
                    width: auto;
                }
            }
        </style>      
    </head>
    <body>
        <div id="top">
            <ul id="nav">
                <?php
                foreach ($this->MenuItems() as $value) {
                    ?>
                    <li class="<?= $value["STATUS"] ?>"><a href="<?= $this->baseUrl() . $value["URL"] ?>"><?= $value["NAME"] ?></a></li>  
                <?php } ?>
            </ul>
        </div>
        <div id="container">
            <div id="sidebar">Left</div>
            <div id="content">
                <div id="data">
                    <?php
                    echo $this->layout()->content;
                    ?> 
                </div>
            </div>
            <div id="footer"></div>
        </div>	
    </body>
</html>