<div id="search">
    <form id="frmSearch" action="" method="post">
        <table>
            <tr>
                <td>Mã người dùng</td>
                <td></td>
                <td><input type="text" id="user_id" name="user_id" value="<?= ($this->userId != "") ? $this->userId : ""; ?>"/></td>
            </tr>
            <tr>
                <td>Họ tên</td>
                <td></td>
                <td><input type="text" id="fullName" name="fullName" value="<?= ($this->name != "") ? $this->name : ""; ?>"/></td>
            </tr>
            <tr>
                <td>Email</td>
                <td></td>
                <td><input type="text" id="email" name="email" value="<?= ($this->email != "") ? $this->email : ""; ?>"/></td>
            </tr>
            <tr>
                <td>Số điện thoại</td>
                <td></td>
                <td><input type="text" id="phone" name="phone" value="<?= ($this->phone != "") ? $this->phone : ""; ?>"/></td>
            </tr>
            <tr>
                <td>Active</td>
                <td></td>
                <td>
                    <select id="active" name="active">
                        <option value="" <?php if ($this->active == "") echo "selected"; ?>>---  Chọn  ---</option>
                        <option value="Y" <?php if ($this->active == "Y") echo "selected"; ?>>Yes</option>
                        <option value="N" <?php if ($this->active == "N") echo "selected"; ?>>No</option>
                    </select>
                </td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td><input type="submit" onclick="javascript:showMessage();" id="btnSearch" name="btnSearch" value="Tìm kiếm"/></td>
            </tr>
        </table>
    </form>
    <div align="right"><a href="<?= $this->baseUrl(); ?>/portal/user/add">Thêm mới</a></div>
</div>
<table class="tableView" width="100%">
    <thead>
        <tr>
            <th>User ID</th>
            <th>Họ tên</th>
            <th>Email</th>
            <th>Số điện thoại</th>
            <th>Địa chỉ</th>
            <th>Ngày tạo</th>
            <th>Người tạo</th>
            <th>Active</th>
            <th>Role</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php
        if (isset($this->dataPaginator) && count($this->dataPaginator) > 0) {
            foreach ($this->dataPaginator as $key => $value) {
                ?>
                <tr>
                    <td><?= $value['USER_LOGIN_ID']; ?></td>
                    <td><?= $value['FULLNAME']; ?></td>
                    <td><?= $value['EMAIL']; ?></td>
                    <td><?= $value['PHONE']; ?></td>
                    <td><?= $value['ADDRESS']; ?></td>
                    <td><?= date('d/m/Y H:i:s', strtotime($value['CREATED_DATE'])); ?></td>
                    <td><?= $value['CREATED_BY_USER_LOGIN']; ?></td>
                    <td><a href="<?= $this->url(array('controller' => 'user', 'action' => 'active', 'module' => 'portal', 'id' => $value['USER_LOGIN_ID'], 'value' => $value['ENABLED'] == "Y" ? "N" : "Y")); ?>" onclick=" return CheckDel('Bạn có chắc muốn thực hiện?');"><?= $value['ENABLED'] == "Y" ? "<span style='color:#1F9D51;'>Yes</span>" : "<span style='color:red;'>No</span>"; ?></a></td>
                    <td><?= ($value['USER_ROLE'] == 2) ? "Admin" : "User"; ?></td>
                    <td><a href="<?= $this->url(array('controller' => 'user', 'action' => 'edit', 'module' => 'portal', 'id' => $value['USER_LOGIN_ID'])); ?>">Sửa</a>
                        | <a href="<?= $this->url(array('controller' => 'user', 'action' => 'delete', 'module' => 'portal', 'id' => $value['USER_LOGIN_ID'])); ?>" onclick=" return CheckDel('Bạn có chắc muốn xóa?');">Xóa</a> </td>
                </tr>
                <?php
            }
        } else {
            ?>
            <tr>
                <td colspan="11">Không có thông tin người dùng.</td>
            </tr>   
        <?php } ?>
        <tr>
            <td colspan="11" style="background-color: #DDD;">
                <?php
                echo $this->paginationControl($this->dataPaginator, 'Sliding', 'pagination.phtml');
                ?>
            </td>
        </tr>      
    </tbody>
</table>
